on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
name: run-rchk

jobs:
  run-rchk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/run-rchk@master